version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=link_harvester
      - DB_USERNAME=root
      - DB_PASSWORD=password
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./src:/var/www/html
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: link_harvester
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - app-network

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scheduler
    working_dir: /var/www/html
    command: php artisan schedule:run
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
